# Generated by Django 5.1.1 on 2024-09-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emial',
            new_name='email',
        ),
    ]
