# Generated by Django 5.1.1 on 2024-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_recepie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
