# Generated by Django 5.1.1 on 2024-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_recepie_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepie',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
